version: '3.8'
#containers => services
services:
  mysql-springboot-container:
    image: mysql:8.0.28
    container_name: mysql-springboot-container
    ports:
      - 3310:3306
    volumes:
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config-deamond:/etc/mysql/conf.d
    networks:
      - backend
    environment:
      MYSQL_USER: khai
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: StudentManagement
  springboot-docker-container:
    image: trinhkhai/project:v1.0.1
    container_name: project
    ports:
      - 8085:8083
    volumes:
      - ./:/app
    networks:
      - backend
#create network
networks:
  backend:
    name: project-network
volumes:
  mysql-springboot-data:
  mysql-springboot-config-deamond: